server:
  port: 1121

eureka:
  client:
    serviceUrl:
          defaultZone: http://eureka1110.com:1110/eureka/ #eureka服务注册地址
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: config-server1121.com  #自定义服务名称
    prefer-ip-address: true  #访问路径可以显示IP地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/microservice-ad/microservice.git #git仓库地址
      #    basedir: config-repo 
          searchPaths: /config-repo/**/*  #搜索路径
          username: 1433251272@qq.com
          password: yd19931230
  application:
    name: config-server

management:
  security: 
    enabled: false #禁用actuator鉴权
    
endpoints:
  shutdown:
    sensitive: false  #禁用密码验证