# Tomcat
server:
    port: 1110
    
spring:
  application:
    name: Eurekaserver1110
    
eureka:
  instance:
    hostname: eureka1110.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #单机
#      defaultZone: http://eureka1110.com:1110/eureka/
#      defaultZone: http://eureka1111.com:1111/eureka/
